[package]
name = "evm_signer_cli"
version = "1.0.0"
edition = "2021"
rust-version = "1.89"

[workspace]
resolver = "3"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
serde_json = "1"
logos_tx_decoder = { git = "https://github.com/logos-co/logos-tx-decoder", rev = "ca2e4193bff09ec4d225bf19ebcf5d2f3ab56bbb" }
logos-rust-sdk = { path = "../logos-rust-sdk-src", optional = true }

[features]
default = ["logos_module"]
logos_module = ["dep:logos-rust-sdk"]
